name: Reusable build and test workflow ğŸ—ï¸

on:
  workflow_call:
    inputs:
      RELEASE_ASSETS:
        description: 'A comma-seperated list of assets which should be uploaded to a release'
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        description: 'SonarCloud access token for analyzing the project'
        required: true

jobs:
  build:
    name: Build project ğŸ› ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
      - name: Cache gradle related files ğŸ—„ï¸
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK âš™ï¸
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Building project ğŸ› ï¸
        run: ./gradlew compileJava
  check:
    name: Check project ğŸ§ª
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache gradle related files ğŸ—„ï¸
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK âš™ï¸
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Running Checkstyle ğŸ§ª
        run: ./gradlew checkstyleMain checkstyleTest
  test:
    name: Test project ğŸ“Š
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache gradle related files ğŸ—„ï¸
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache SonarCloud packages ğŸ—„ï¸
        uses: actions/cache@v2.1.7
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Set up JDK âš™ï¸
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Running tests ğŸ§ª
        run: ./gradlew test
      - name: Running analysis in SonarCloud ğŸ“Š
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew sonarqube
  release:
    name: Release assets ğŸš€
    runs-on: ubuntu-latest
    needs: [ test, check ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache gradle related files ğŸ—„ï¸
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $(echo {{ inputs.RELEASE_ASSETS }} | tr "," "\n")
