name: Reusable compile and deploy docs workflow ğŸ“š

on: [workflow_call]

jobs:
  compile-and-deploy:
    name: Compile and deploy Javadoc ğŸ“š 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set up JDK âš™ï¸
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile JavaDoc ğŸ”§
        run: ./gradlew javadoc
      - name: Extract release âœ‚ï¸
        shell: bash
        run: echo "##[set-output name=release;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_release
      - name: Deploy latest docs ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: build/docs/javadoc
          git-config-name: Kryonite Docs
          git-config-email: docs@kryonite.org
          target-folder: latest
      - name: Deploy versioned docs ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: docs
          folder: build/docs/javadoc
          git-config-name: Kryonite Docs
          git-config-email: docs@kryonite.org
          target-folder: ${{ steps.extract_release.outputs.release }} 
