name: Reusable Release Drafter workflow

on: [workflow_call]

jobs:
  update-release-draft:
    name: Update release draft ğŸ—’ï¸
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.17.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
