name: Reusable Gradle Wrapper validation workflow

on: [workflow_call]

jobs:
  validation:
    name: Gradle Wrapper Validation âœ…
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper âœ…
        uses: gradle/wrapper-validation-action@v1.0.4
